### ISSUE TITLE
custom participant_id claims format

### ISSUE THREAD

**Issue by koriaf** [ausdigital/ausdigital-idp#8]
The ability to use custom claims in IDP JWT tokens is descirbed, and I need to know which exact claims client software may expect.

Desired action: extract participant ID from given JWT token.
Current implementation on idp.testpoint.io: JWT contains `"abn": 9999999999` claim, and client software prepends `urn:oasis:names:tc:ebcore:partyid-type:iso6523:9999::` to it to get participant ID (where 9999 is a ISO6523 value for ABN).
Desired state: it's clearly described which claims are used for specific business identifiers types, or it's clearly described that it's IDP-specific.

Personnaly I like `"participant_id": "urn:oasis:names:tc:ebcore:partyid-type:iso6523:0151::43999999999"`, which is universal, but quite verbose. `"abn": 99999999` is short, but very collision-prone (and OIDC protocol says that custom claims shall be prefixed somehow uniquely).

**Comment by monkeypants** [comment]
I think use of oasis ISO6525 urns in jwt claims would be a definite improvement.

**Comment by koriaf** [comment]
What this claim will be named? http://ausdigital.org/specs/ausdigital-idp/1.0/#custom-claims-and-scopes-in-the-adbc-idp-domain here it's described that claim should exist, but no examples or specific claim format provided.

JWT spec says that custom claims may be of 2 types: public and private. Public shall be registered (http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#rfc.section.4.2 here), and private may have any collision-resistant format, which is understood by any party which use the token. Private format is described http://self-issued.info/docs/draft-ietf-oauth-json-web-token.html#URNReg here.

* Some examples over the net use `org.orgname.param1.param2...` claim name.
* spec use `urn:ietf:params:oauth:grant-type:example` format
* also, people use `urn:www.sitename.dn:innernamespace:parameter`

So I think we need something like `urn:ausdigital:idp:participant-id`, but not sure about exact value. And JWT will have structure like this:
```
{
   "iss": "http://idp.testpoint.io",
   ...
   "urn:ausdigital:idp:participant-id": "urn:oasis:names:tc:ebcore:partyid-type:iso6523:0151::1234567890"
}
```

**Comment by monkeypants** [comment]
Instead of making our own key (claim name), we should split the oasis urn on the `::`. In other words, the key would be `urn:oasis:names:tc:ebcore:partyid-type:iso6523:0151` and the value would be the 11 digit ABN.

If there are other well known URNs (outside OASIS) we should use them too. For example, imagine if one day there was a urn like `abr.gov.au/abn`, we could also use it for a claim name (and have the same 11 digit value for the value of the claim). In that hypothetical example, we might expect both claims to co-exist in the same JWT.

**Comment by koriaf** [comment]
that's amazing. so client just checks any key which starts with urn:oasis:names:tc:ebcore:partyid-type:iso6523: and checks if he wants to support 0151 and then read the value. Or just silently concats it, validates quickly and uses.

**Comment by monkeypants** [comment]
The claim means "my ABN is 12345678901". It has two parts, "identifier scheme" (ABN) and "identity in the context of that scheme" (12345678901). We could have multiple identifiers, for example `urn:oasis:names:tc:SAML:1.1:nameid-format:` : `kites-r-us@gmail.com`

I think maybe we should describe this as "URN namespace" is the key of the custom JWT claim, and is equivalent to the "identifier scheme". The value of the custom JWT claim the string that, when concatenated to the namespace, forms the URN of the resource (the URN of the claimed identity).

**Comment by koriaf** [comment]
Status: I'm pretty happy with current format, supported by all testpoint implementations. For example:
```
"urn:oasis:names:tc:ebcore:partyid-type:unregistered": [
    {
      "ibr-account": "148c5c13-5653-4b1b-9d1e-b5bdd610042a"
    }
  ],
  "urn:oasis:names:tc:ebcore:partyid-type:iso6523": [
    {
      "0151": "89907568451",
      "0088": "1465588979895"
    }
  ],
```

**Comment by monkeypants** [comment]
me too
